-- ==============================================================================
-- Migration: 20260926000002_create_ideas_and_tags.sql
-- Description: Create ideas, tags, and idea_tags tables with RLS and composite indexes.
-- ==============================================================================

-- 1. Create ideas table
CREATE TABLE IF NOT EXISTS public.ideas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    idea_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (char_length(trim(title)) > 0),
    description TEXT,           -- Original Spark
    problem TEXT,               -- Why It Matters
    target_users TEXT,          -- Target audience / users
    potential_direction TEXT,   -- Potential Direction & architecture angle
    hypothesis TEXT,            -- Quick hypothesis / key bet
    workshop_notes JSONB NOT NULL DEFAULT '[]'::jsonb, -- Workshop Notes & Scratches
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'exploring', 'building', 'converted', 'archived')),
    stage TEXT NOT NULL DEFAULT 'captured' CHECK (stage IN ('captured', 'explored', 'forge', 'building', 'rebuild')),
    revisions_count INT NOT NULL DEFAULT 1 CHECK (revisions_count >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create tags table
CREATE TABLE IF NOT EXISTS public.tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (char_length(trim(name)) > 0),
    color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Create idea_tags junction table
CREATE TABLE IF NOT EXISTS public.idea_tags (
    idea_id UUID NOT NULL REFERENCES public.ideas(id) ON DELETE CASCADE,
    tag_id UUID NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (idea_id, tag_id)
);

-- 4. Composite & Performance Indexes
-- Ideas indexes
CREATE INDEX IF NOT EXISTS idx_ideas_user_status ON public.ideas (user_id, status);
CREATE INDEX IF NOT EXISTS idx_ideas_user_stage ON public.ideas (user_id, stage);
CREATE INDEX IF NOT EXISTS idx_ideas_user_created_at ON public.ideas (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ideas_user_updated_at ON public.ideas (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ideas_user_number ON public.ideas (user_id, idea_number);

-- Tags indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_user_name_unique ON public.tags (user_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_tags_user_created_at ON public.tags (user_id, created_at DESC);

-- Idea tags composite reverse lookup index
CREATE INDEX IF NOT EXISTS idx_idea_tags_tag_idea ON public.idea_tags (tag_id, idea_id);

-- 5. Enable Row-Level Security (RLS)
ALTER TABLE public.ideas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.idea_tags ENABLE ROW LEVEL SECURITY;

-- 6. Row-Level Security Policies

-- ideas RLS
CREATE POLICY "Users can view their own ideas"
    ON public.ideas
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own ideas"
    ON public.ideas
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own ideas"
    ON public.ideas
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own ideas"
    ON public.ideas
    FOR DELETE
    USING (auth.uid() = user_id);

-- tags RLS
CREATE POLICY "Users can view their own tags"
    ON public.tags
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own tags"
    ON public.tags
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tags"
    ON public.tags
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tags"
    ON public.tags
    FOR DELETE
    USING (auth.uid() = user_id);

-- idea_tags RLS
CREATE POLICY "Users can view tags on their own ideas"
    ON public.idea_tags
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.ideas
            WHERE ideas.id = idea_tags.idea_id
              AND ideas.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can link tags to their own ideas"
    ON public.idea_tags
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.ideas
            WHERE ideas.id = idea_tags.idea_id
              AND ideas.user_id = auth.uid()
        )
        AND
        EXISTS (
            SELECT 1 FROM public.tags
            WHERE tags.id = idea_tags.tag_id
              AND tags.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can unlink tags from their own ideas"
    ON public.idea_tags
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.ideas
            WHERE ideas.id = idea_tags.idea_id
              AND ideas.user_id = auth.uid()
        )
    );

-- 7. Updated_at Trigger for ideas
DROP TRIGGER IF EXISTS set_ideas_updated_at ON public.ideas;
CREATE TRIGGER set_ideas_updated_at
    BEFORE UPDATE ON public.ideas
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();
